### ISSUE TITLE
显示没有实体

### ISSUE THREAD

**Issue by zhishike1991** [mypal/ha-hitachi#1]
![7df31953388bf128531e9b001df9073](https://github.com/user-attachments/assets/42936a8d-1cc6-4560-929d-789b940e0e0f)

**Comment by mypal** [comment]
可以提供下报错日志

**Comment by kuoruan** [comment]
一样的情况

```
2024-12-20 10:18:42.149 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fb67adee8d0>,) inside the event loop by custom integration 'hitachi' at custom_components/hitachi/request.py, line 53: async with get_client() as client: (offender: /usr/local/lib/python3.13/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please report it to the author of the 'hitachi' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 559, in start
    task = asyncio.Task(coro, loop=loop, eager_start=True)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
  File "/config/custom_components/hitachi/config_flow.py", line 39, in async_step_user
    res = await refresh_auth(self.user_input[CONF_USERNAME], self.user_input[CONF_PASSWORD])
  File "/config/custom_components/hitachi/request.py", line 106, in refresh_auth
    par = parse_auth_res(await login(username, password))
  File "/config/custom_components/hitachi/request.py", line 68, in login
    return await _post('login', {
  File "/config/custom_components/hitachi/request.py", line 53, in _post
    async with get_client() as client:

```

**Comment by mypal** [comment]
> 一样的情况
> 
> ```
> 2024-12-20 10:18:42.149 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fb67adee8d0>,) inside the event loop by custom integration 'hitachi' at custom_components/hitachi/request.py, line 53: async with get_client() as client: (offender: /usr/local/lib/python3.13/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please report it to the author of the 'hitachi' custom integration
> For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
>     sys.exit(main())
>   File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
>     exit_code = runner.run(runtime_conf)
>   File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
>     return loop.run_until_complete(setup_and_run_hass(runtime_config))
>   File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
>     self.run_forever()
>   File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
>     self._run_once()
>   File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
>     handle._run()
>   File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
>     self._context.run(self._callback, *self._args)
>   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 559, in start
>     task = asyncio.Task(coro, loop=loop, eager_start=True)
>   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
>     resp = await request_handler(request)
>   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
>     return await handler(request)
>   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
>     response = await handler(request)
>   File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
>     result = await handler(request, **request.match_info)
>   File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
>     return await func(self, request, *args, **kwargs)
>   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
>     return await super().post(request, flow_id)
>   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
>     return await method(view, request, data, *args, **kwargs)
>   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
>     result = await self._flow_mgr.async_configure(flow_id, data)
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
>     result = await self._async_configure(flow_id, user_input)
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
>     result = await self._async_handle_step(
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
>     result: _FlowResultT = await getattr(flow, method)(user_input)
>   File "/config/custom_components/hitachi/config_flow.py", line 39, in async_step_user
>     res = await refresh_auth(self.user_input[CONF_USERNAME], self.user_input[CONF_PASSWORD])
>   File "/config/custom_components/hitachi/request.py", line 106, in refresh_auth
>     par = parse_auth_res(await login(username, password))
>   File "/config/custom_components/hitachi/request.py", line 68, in login
>     return await _post('login', {
>   File "/config/custom_components/hitachi/request.py", line 53, in _post
>     async with get_client() as client:
> ```

这个告警不影响功能，不显示实体有可能是不支持的面板型号。可以先确认下面板是啥型号

**Comment by kuoruan** [comment]
我这边的线控器全部是：PC-P1HEQ2

**Comment by mypal** [comment]
> 我这边的线控器全部是：PC-P1HEQ2

唔，这个插件目前只支持SXC-TE01，我在论坛有提到，README里面我也加一下吧。如果你的面板也是用日立智家APP，控制流程应当相似，能提供API抓包日志的话，可以扩展一下

**Comment by Surfire** [comment]
小哥我们有一个全国的水机空调爱好者群 有没有兴趣加入 @mypal

**Comment by kiwiwiki007** [comment]
我也是没有实体或设备，我家的是PC-P1H9QA面板，我可以提供抓包信息。需要那些抓包信息

**Comment by mypal** [comment]
> 小哥我们有一个全国的水机空调爱好者群 有没有兴趣加入 [@mypal](https://github.com/mypal)

咋加

**Comment by mypal** [comment]
> 我也是没有实体或设备，我家的是PC-P1H9QA面板，我可以提供抓包信息。需要那些抓包信息

日立这个就是纯https的请求，APP启动到操作过程的请求全抓出来就是了

**Comment by ukzhangjin** [comment]
为啥我是用户名密码错我啊  我日立智家明明能登录的啊

**Comment by mypal** [comment]
> 为啥我是用户名密码错我啊 我日立智家明明能登录的啊

日志具体啥报错
